### PR TITLE
moving to jakarta

### PR DESCRIPTION
**Pull request by amoscatelli**
Hi @chengfang !
Is this ok for you ?

Let me know !

### CODE REVIEW

**Comment by chengfang** [comment]
any idea why CORSFilter is causing errors? It worked before.

**Comment by amoscatelli** [comment]
Returning * as allowed domain is not accepted anymore by browsers.
The proper behaviour should be returning the exact domain sending the OPTION request.

All of chrome, firefox and edge are complaining about this resulting in a cors error.

CORSFilter register itself automatically and breaks everything without possibility of disabling it.

Also, CORSFilter seems a bit out of scope for this library.

CORS request should be handled by another library or by the application server itself.

For example, I configured an undertow filter (in standalone.xml) in Wildfly to manage cors requests.

**Comment by chengfang** [comment]
can you share the undertow filter (in standalone.xml) in Wildfly to manage cors requests?

**Comment by amoscatelli** [comment]
Sure thing !

```
            <filters>
                <expression-filter name="Access-Control-Allow-Origin" expression="exists('%{i,Origin}') and regex(pattern='\b(?:${env.cors.whitelist})(;.*)?\b', value=%{i,Origin}, full-match=true) -&gt; set(attribute='%{o,Access-Control-Allow-Origin}', value='%{i,Origin}')"/>
                <expression-filter name="Access-Control-Allow-Methods" expression="exists('%{i,Origin}') and regex(pattern='\b(?:${env.cors.whitelist})(;.*)?\b', value=%{i,Origin}, full-match=true) -&gt; set(attribute='%{o,Access-Control-Allow-Methods}', value='GET, POST, OPTIONS, PUT, DELETE')"/>
                <expression-filter name="Access-Control-Allow-Headers" expression="exists('%{i,Origin}') and regex(pattern='\b(?:${env.cors.whitelist})(;.*)?\b', value=%{i,Origin}, full-match=true) -&gt; set(attribute='%{o,Access-Control-Allow-Headers}', value='${env.cors.headers}')"/>
                <expression-filter name="Access-Control-Allow-Credentials" expression="exists('%{i,Origin}') and regex(pattern='\b(?:${env.cors.whitelist})(;.*)?\b', value=%{i,Origin}, full-match=true) -&gt; set(attribute='%{o,Access-Control-Allow-Credentials}', value='true')"/>
                <expression-filter name="Access-Control-Max-Age" expression="exists('%{i,Origin}') and regex(pattern='\b(?:${env.cors.whitelist})(;.*)?\b', value=%{i,Origin}, full-match=true) -&gt; set(attribute='%{o,Access-Control-Max-Age}', value='1')"/>
            </filters>
```

cors.whitelist and cors.headers can be defined as system properties (always in standalone.xml) :

```
        <property name="env.cors.whitelist" value=".*"/>
        <property name="env.cors.headers" value="Authorization,Content-Type,Content-Encoding,Link,X-Total-Count,Range,elastic-apm-traceparent,traceparent,X-Grant,X-Transaction-Id,X-Captcha,x-b3-traceid,x-b3-spanid,x-b3-sampled,x-amzn-trace-id,uber-trace-id,traceparent"/>
```
     
or as environment variables :

```   
cors.whitelist=.*
cors.headers=Authorization,Content-Type,Content-Encoding,Link,X-Total-Count,Range,elastic-apm-traceparent,traceparent,X-Grant,X-Transaction-Id,X-Captcha,x-b3-traceid,x-b3-spanid,x-b3-sampled,x-amzn-trace-id,uber-trace-id
```

**Review by chengfang — APPROVED** [review]

**Comment by amoscatelli** [comment]
@chengfang can this be merged too ?

**Pull request merged**
